all: false
dir: '{{.InterfaceDir}}/mocks'
filename: mocks.go
force-file-write: true
formatter: goimports
log-level: error
pkgname: 'mocks'
recursive: false
template: testify
structname: '{{.InterfaceName}}'
packages:
  github.com/amagkn/golang-production-ready-reference/internal/usecase:
    config:
      all: True
